UPDATE posts_locales SET body_markdown = E'# The Containment Age\n\nSoftware engineering entered a phase of **radical containment**. The era of the open-ended prompt is closing — replaced by the necessity of the *bounded pipeline*. We no longer ask what a model can do; we define what it **must not** do.\n\n## The Contractual Layer\n\nEvery LLM invocation must be wrapped in a contract. If input does not match schema, the process refuses to initiate. If output diverges from expected structure, it is rejected and re-routed.\n\n> Unsupported claims return uncertainty, not prose. Silence is a feature of a robust system.\n\n## Deterministic Edges\n\nWhile the core may be probabilistic, the edges remain deterministic:\n\n- Classifiers, extractors, validators — pure functions\n- Schemas at every interface\n- No "creative latitude" where correctness is required\n\n```ts\nconst ClaimSchema = z.object({\n  subject: z.string(),\n  predicate: z.enum(["observed", "inferred", "cited"]),\n  evidence_id: z.string().uuid(),\n});\n```\n\n## Ship to Learn\n\nDeploy small. Instrument everything. Iterate against real usage. Velocity *with* judgment is the whole job.\n\n---\n\nMore posts — see [journal](/journal).\n' WHERE _locale='en' AND _parent_id=1;

UPDATE posts_locales SET body_markdown = E'# Vibe Discipline\n\nSpeed and rigor are orthogonal. Here is how we hold both.\n\n## The trap\n\nTeams pick a lane: *move fast*, or *ship safely*. Both lanes are wrong.\n\n## The pattern\n\n1. Contract first\n2. Smallest shippable slice\n3. Telemetry on day zero\n\n**Rigor** is infrastructure — it compounds. **Velocity** is cadence — it doesn''t.\n\n---\n\nSee also: [Bounded LLMs](/journal/bounded-llms).\n' WHERE _locale='en' AND _parent_id=2;

UPDATE posts_locales SET body_markdown = E'# Qwen Hackathon — 2nd Place Postmortem\n\n200+ teams. 48 hours. 2nd place, Best Use of Qwen.\n\n## What we cut\n\n- Multi-agent orchestration — one agent, one job\n- "Learning from feedback" — static eval only\n- UI polish past what the judges would see in 4 minutes\n\n## What we kept\n\n- The **tag contract**\n- The memory adapter\n- Hard refusals on uncited claims\n\n## What we''d do again\n\nEverything — in half the time.\n' WHERE _locale='en' AND _parent_id=3;

UPDATE posts_locales SET body_markdown = E'# Agentic Meta — The Shape of the Club\n\nA club is a forcing function. Here is ours.\n\n## Charter\n\nWe teach *engineering against indeterminacy*. We don''t teach prompt engineering.\n\n## Cohort design\n\n- First-years preferred\n- Evidence over credential\n- Public artifacts only\n\n## What we publish\n\nContracts, benchmarks, failure logs. If you cannot see the failures, you cannot trust the system.\n' WHERE _locale='en' AND _parent_id=4;

SELECT _parent_id, length(body_markdown) AS md_len FROM posts_locales WHERE _locale='en';
